version: '2'

services:

    php_sl:
        container_name: php_sl
        image: phalconphp-3.0.2/php:7.0-fpm
        networks:
            nw_sl:
                ipv4_address: 172.30.0.20
        volumes:
            - /docker/locaweb/www/locaweb/:/var/www/locaweb/
            - /docker/locaweb/conf/php:/usr/local/etc/php/
            - /docker/locaweb/logs/:/var/log/php/

    locaweb:
        container_name: locaweb
        image: nginx:latest
        ports:
            - 91:91
        networks:
            nw_sl:
                ipv4_address: 172.30.0.30
        volumes:
            - /docker/locaweb/conf/nginx/:/etc/nginx/conf.d/
            - /docker/locaweb/logs/:/var/log/nginx/
            - /docker/locaweb/www/locaweb/:/var/www/locaweb/
        links:
            - php_sl

networks:

    nw_sl:
        ipam:
            driver: default
            config:
                 - subnet: 172.30.0.0/16
